export const electives = [
  {
    id: 1,
    courseName: 'Introduction to Programming',
    courseCode: 'CS101',
    faculty: 'Dr. John Doe',
    totalSeats: 50,
    remainingSeats: 20,
  },
  {
    id: 2,
    courseName: 'Data Structures and Algorithms',
    courseCode: 'CS102',
    faculty: 'Prof. Jane Smith',
    totalSeats: 60,
    remainingSeats: 35,
  },
  {
    id: 3,
    courseName: 'Database Management Systems',
    courseCode: 'CS103',
    faculty: 'Dr. Emily Clark',
    totalSeats: 45,
    remainingSeats: 10,
  },
  {
    id: 4,
    courseName: 'Operating Systems',
    courseCode: 'CS104',
    faculty: 'Prof. Mike Johnson',
    totalSeats: 40,
    remainingSeats: 5,
  },
  {
    id: 5,
    courseName: 'Discrete Mathematics',
    courseCode: 'CS105',
    faculty: 'Dr. Sarah Williams',
    totalSeats: 30,
    remainingSeats: 12,
  },
  {
    id: 6,
    courseName: 'Computer Networks',
    courseCode: 'CS106',
    faculty: 'Dr. Robert Green',
    totalSeats: 50,
    remainingSeats: 25,
  },
  {
    id: 7,
    courseName: 'Software Engineering',
    courseCode: 'CS107',
    faculty: 'Prof. Angela White',
    totalSeats: 60,
    remainingSeats: 40,
  },
  {
    id: 8,
    courseName: 'Artificial Intelligence',
    courseCode: 'CS108',
    faculty: 'Prof. Thomas Lee',
    totalSeats: 45,
    remainingSeats: 15,
  },
  {
    id: 9,
    courseName: 'Web Development',
    courseCode: 'CS109',
    faculty: 'Dr. Olivia Brown',
    totalSeats: 50,
    remainingSeats: 30,
  },
  {
    id: 10,
    courseName: 'Machine Learning',
    courseCode: 'CS110',
    faculty: 'Prof. Brian Black',
    totalSeats: 55,
    remainingSeats: 20,
  },
  {
    id: 11,
    courseName: 'Cloud Computing',
    courseCode: 'CS111',
    faculty: 'Dr. Kevin White',
    totalSeats: 40,
    remainingSeats: 25,
  },
  {
    id: 12,
    courseName: 'Cybersecurity',
    courseCode: 'CS112',
    faculty: 'Prof. Rachel Adams',
    totalSeats: 45,
    remainingSeats: 15,
  },
  {
    id: 13,
    courseName: 'Data Science',
    courseCode: 'CS113',
    faculty: 'Dr. Daniel Scott',
    totalSeats: 50,
    remainingSeats: 30,
  },
  {
    id: 14,
    courseName: 'Computer Graphics',
    courseCode: 'CS114',
    faculty: 'Prof. Susan Lee',
    totalSeats: 60,
    remainingSeats: 40,
  },
  {
    id: 15,
    courseName: 'Algorithm Design',
    courseCode: 'CS115',
    faculty: 'Dr. Gary Nelson',
    totalSeats: 50,
    remainingSeats: 20,
  },
  {
    id: 16,
    courseName: 'Human-Computer Interaction',
    courseCode: 'CS116',
    faculty: 'Prof. Carol Moore',
    totalSeats: 45,
    remainingSeats: 25,
  },
  {
    id: 17,
    courseName: 'Mobile App Development',
    courseCode: 'CS117',
    faculty: 'Dr. Brian Miller',
    totalSeats: 40,
    remainingSeats: 15,
  },
  {
    id: 18,
    courseName: 'Blockchain Technology',
    courseCode: 'CS118',
    faculty: 'Prof. Olivia Turner',
    totalSeats: 50,
    remainingSeats: 30,
  },
  {
    id: 19,
    courseName: 'Virtual Reality',
    courseCode: 'CS119',
    faculty: 'Dr. Henry Walker',
    totalSeats: 60,
    remainingSeats: 45,
  },
  {
    id: 20,
    courseName: 'Quantum Computing',
    courseCode: 'CS120',
    faculty: 'Prof. George Carter',
    totalSeats: 30,
    remainingSeats: 10,
  },
];
