const allUsers = [
  {
    name: "John Doe",
    registrationNo: "BTECH1234",
    mobileNo1: "+1234567890",
    mobileNo2: "+0987654321",
    departmentName: "CSE",
    branchName: "Software Engineering",
    semester: "5",
    classCoordinator: true,
    profilePic: null, // Placeholder or URL
    classCoordinatorName: "Dr. Jane Smith",
    mailId: "john.doe@example.com",
    section: "A",
    batchNo: "2021",
    gender: "Male",
    elective: { subject: "Data Science", credits: 3 }
  },
  {
    name: "Jane Smith",
    registrationNo: "BTECH5678",
    mobileNo1: "+1234567891",
    mobileNo2: "+0987654322",
    departmentName: "ECE",
    branchName: "Electrical Engineering",
    semester: "3",
    classCoordinator: false,
    profilePic: null, // Placeholder or URL
    classCoordinatorName: "",
    mailId: "jane.smith@example.com",
    section: "B",
    batchNo: "2022",
    gender: "Female",
    elective: { subject: "AI Basics", credits: 2 }
  },
  {
    name: "Mike Johnson",
    registrationNo: "BTECH9101",
    mobileNo1: "+1234567892",
    mobileNo2: "+0987654323",
    departmentName: "ME",
    branchName: "Mechanical Engineering",
    semester: "7",
    classCoordinator: true,
    profilePic: null, // Placeholder or URL
    classCoordinatorName: "Dr. Alan Cooper",
    mailId: "mike.johnson@example.com",
    section: "C",
    batchNo: "2020",
    gender: "Male",
    elective: { subject: "Robotics", credits: 4 }
  },
  {
    name: "Sara Brown",
    registrationNo: "BTECH1123",
    mobileNo1: "+1234567893",
    mobileNo2: "+0987654324",
    departmentName: "IT",
    branchName: "Information Technology",
    semester: "1",
    classCoordinator: false,
    profilePic: null, // Placeholder or URL
    classCoordinatorName: "",
    mailId: "sara.brown@example.com",
    section: "A",
    batchNo: "2023",
    gender: "Female",
    elective: { subject: "Cybersecurity", credits: 3 }
  },
  {
    name: "Robert Green",
    registrationNo: "BTECH1617",
    mobileNo1: "+1234567894",
    mobileNo2: "+0987654325",
    departmentName: "CSE",
    branchName: "Computer Science",
    semester: "6",
    classCoordinator: true,
    profilePic: null, // Placeholder or URL
    classCoordinatorName: "Dr. Rachel Adams",
    mailId: "robert.green@example.com",
    section: "B",
    batchNo: "2021",
    gender: "Male",
    elective: { subject: "Machine Learning", credits: 3 }
  },
  {
    name: "Laura Black",
    registrationNo: "BTECH1819",
    mobileNo1: "+1234567895",
    mobileNo2: "+0987654326",
    departmentName: "ECE",
    branchName: "Electrical Engineering",
    semester: "2",
    classCoordinator: false,
    profilePic: null, // Placeholder or URL
    classCoordinatorName: "",
    mailId: "laura.black@example.com",
    section: "C",
    batchNo: "2023",
    gender: "Female",
    elective: { subject: "Embedded Systems", credits: 2 }
  },
  {
    name: "Chris Adams",
    registrationNo: "BTECH2021",
    mobileNo1: "+1234567896",
    mobileNo2: "+0987654327",
    departmentName: "ME",
    branchName: "Mechanical Engineering",
    semester: "4",
    classCoordinator: false,
    profilePic: null, // Placeholder or URL
    classCoordinatorName: "",
    mailId: "chris.adams@example.com",
    section: "D",
    batchNo: "2022",
    gender: "Male",
    elective: { subject: "Thermodynamics", credits: 3 }
  },
  {
    name: "Amy Clark",
    registrationNo: "BTECH2223",
    mobileNo1: "+1234567897",
    mobileNo2: "+0987654328",
    departmentName: "IT",
    branchName: "Information Technology",
    semester: "8",
    classCoordinator: true,
    profilePic: null, // Placeholder or URL
    classCoordinatorName: "Dr. Megan White",
    mailId: "amy.clark@example.com",
    section: "A",
    batchNo: "2019",
    gender: "Female",
    elective: { subject: "Cloud Computing", credits: 4 }
  },
  {
    name: "David Lewis",
    registrationNo: "BTECH2425",
    mobileNo1: "+1234567898",
    mobileNo2: "+0987654329",
    departmentName: "CE",
    branchName: "Civil Engineering",
    semester: "5",
    classCoordinator: false,
    profilePic: null, // Placeholder or URL
    classCoordinatorName: "",
    mailId: "david.lewis@example.com",
    section: "B",
    batchNo: "2020",
    gender: "Male",
    elective: { subject: "Environmental Science", credits: 3 }
  },
  {
    name: "Rachel Wilson",
    registrationNo: "BTECH2627",
    mobileNo1: "+1234567899",
    mobileNo2: "+0987654330",
    departmentName: "CSE",
    branchName: "Computer Science",
    semester: "3",
    classCoordinator: false,
    profilePic: null, // Placeholder or URL
    classCoordinatorName: "",
    mailId: "rachel.wilson@example.com",
    section: "A",
    batchNo: "2022",
    gender: "Female",
    elective: { subject: "Web Development", credits: 2 }
  },
  {
    name: "Brian Martinez",
    registrationNo: "BTECH2829",
    mobileNo1: "+1234567800",
    mobileNo2: "+0987654331",
    departmentName: "ECE",
    branchName: "Electronics",
    semester: "1",
    classCoordinator: true,
    profilePic: null, // Placeholder or URL
    classCoordinatorName: "Dr. Samuel Harris",
    mailId: "brian.martinez@example.com",
    section: "C",
    batchNo: "2023",
    gender: "Male",
    elective: { subject: "Digital Electronics", credits: 3 }
  },
  {
    name: "Olivia Scott",
    registrationNo: "BTECH3031",
    mobileNo1: "+1234567801",
    mobileNo2: "+0987654332",
    departmentName: "ME",
    branchName: "Mechanical Engineering",
    semester: "7",
    classCoordinator: false,
    profilePic: null, // Placeholder or URL
    classCoordinatorName: "",
    mailId: "olivia.scott@example.com",
    section: "A",
    batchNo: "2020",
    gender: "Female",
    elective: { subject: "Fluid Mechanics", credits: 4 }
  },
  {
    name: "Jack Thomas",
    registrationNo: "BTECH3233",
    mobileNo1: "+1234567802",
    mobileNo2: "+0987654333",
    departmentName: "IT",
    branchName: "Information Technology",
    semester: "6",
    classCoordinator: true,
    profilePic: null, // Placeholder or URL
    classCoordinatorName: "Dr. Emma Clark",
    mailId: "jack.thomas@example.com",
    section: "B",
    batchNo: "2021",
    gender: "Male",
    elective: { subject: "Data Privacy", credits: 3 }
  },
  {
    name: "Sophia Turner",
    registrationNo: "BTECH3435",
    mobileNo1: "+1234567803",
    mobileNo2: "+0987654334",
    departmentName: "CE",
    branchName: "Civil Engineering",
    semester: "2",
    classCoordinator: false,
    profilePic: null, // Placeholder or URL
    classCoordinatorName: "",
    mailId: "sophia.turner@example.com",
    section: "A",
    batchNo: "2023",
    gender: "Female",
    elective: { subject: "Geotechnical Engineering", credits: 2 }
  },
  {
    name: "Liam Evans",
    registrationNo: "BTECH3637",
    mobileNo1: "+1234567804",
    mobileNo2: "+0987654335",
    departmentName: "CSE",
    branchName: "Computer Science",
    semester: "5",
    classCoordinator: true,
    profilePic: null, // Placeholder or URL
    classCoordinatorName: "Dr. Ethan Black",
    mailId: "liam.evans@example.com",
    section: "B",
    batchNo: "2021",
    gender: "Male",
    elective: { subject: "Artificial Intelligence", credits: 3 }
  },
  {
    name: "Mia Roberts",
    registrationNo: "BTECH3839",
    mobileNo1: "+1234567805",
    mobileNo2: "+0987654336",
    departmentName: "ECE",
    branchName: "Electronics",
    semester: "4",
    classCoordinator: false,
    profilePic: null, // Placeholder or URL
    classCoordinatorName: "",
    mailId: "mia.roberts@example.com",
    section: "C",
    batchNo: "2022",
    gender: "Female",
    elective: { subject: "Signal Processing", credits: 3 }
  },
  {
    name: "Ethan Baker",
    registrationNo: "BTECH4041",
    mobileNo1: "+1234567806",
    mobileNo2: "+0987654337",
    departmentName: "ME",
    branchName: "Mechanical Engineering",
    semester: "8",
    classCoordinator: false,
    profilePic: null, // Placeholder or URL
    classCoordinatorName: "",
    mailId: "ethan.baker@example.com",
    section: "A",
    batchNo: "2019",
    gender: "Male",
    elective: { subject: "Manufacturing Processes", credits: 4 }
  },
  {
    name: "Ava King",
    registrationNo: "BTECH4243",
    mobileNo1: "+1234567807",
    mobileNo2: "+0987654338",
    departmentName: "IT",
    branchName: "Information Technology",
    semester: "3",
    classCoordinator: false,
    profilePic: null, // Placeholder or URL
    classCoordinatorName: "",
    mailId: "ava.king@example.com",
    section: "B",
    batchNo: "2022",
    gender: "Female",
    elective: { subject: "Network Security", credits: 2 }
  },
  {
    name: "Benjamin Lee",
    registrationNo: "BTECH4445",
    mobileNo1: "+1234567808",
    mobileNo2: "+0987654339",
    departmentName: "CE",
    branchName: "Civil Engineering",
    semester: "1",
    classCoordinator: false,
    profilePic: null, // Placeholder or URL
    classCoordinatorName: "",
    mailId: "benjamin.lee@example.com",
    section: "C",
    batchNo: "2023",
    gender: "Male",
    elective: { subject: "Engineering Graphics", credits: 3 }
  }
];

export default allUsers;


