export const oeChangeRequests = [
  {
    id: 1,
    userId: "29209a4f-18b3-4cf8-84b3-094dfe7e87bd",
    name: "Jake Paul",
    registrationNo: "BTECH1234",
    currentOE: { OEName: "Data Science", courseCode: "DS101" },
    requestedOE: { OEName: "Cyber Security", courseCode: "CS202" },
    remainingSeats: 5,
    status: "Pending",
  },
  {
    id: 2,
    name: "Jane Smith",
    registrationNo: "BTECH5678",
    currentOE: { OEName: "Machine Learning", courseCode: "ML303" },
    requestedOE: { OEName: "Artificial Intelligence", courseCode: "AI404" },
    remainingSeats: 0,
    status: "Pending",
  },
  {
    id: 3,
    name: "Mike",
    registrationNo: "BTECH9101",
    currentOE: { OEName: "Big Data", courseCode: "BD505" },
    requestedOE: { OEName: "Cloud Computing", courseCode: "CC606" },
    remainingSeats: 2,
    status: "Pending",
  },
  {
    id: 4,
    name: "Amy Clark",
    registrationNo: "BTECH2223",
    currentOE: { OEName: "Cloud Computing", courseCode: "CC101" },
    requestedOE: { OEName: "Machine Learning", courseCode: "ML303" },
    remainingSeats: 3,
    status: "Pending",
  },
  {
    id: 5,
    name: "David Lewis",
    registrationNo: "BTECH2425",
    currentOE: { OEName: "Environmental Science", courseCode: "ES202" },
    requestedOE: { OEName: "Artificial Intelligence", courseCode: "AI404" },
    remainingSeats: 2,
    status: "Pending",
  },
  {
    id: 6,
    name: "Rachel Wilson",
    registrationNo: "BTECH2627",
    currentOE: { OEName: "Web Development", courseCode: "WD303" },
    requestedOE: { OEName: "Data Privacy", courseCode: "DP101" },
    remainingSeats: 5,
    status: "Pending",
  },
  {
    id: 7,
    name: "Sophia Turner",
    registrationNo: "BTECH3435",
    currentOE: { OEName: "Geotechnical Engineering", courseCode: "GE201" },
    requestedOE: { OEName: "Digital Electronics", courseCode: "DE102" },
    remainingSeats: 6,
    status: "Pending",
  },
  {
    id: 8,
    name: "Liam Evans",
    registrationNo: "BTECH3637",
    currentOE: { OEName: "Artificial Intelligence", courseCode: "AI303" },
    requestedOE: { OEName: "Cloud Computing", courseCode: "CC404" },
    remainingSeats: 0,
    status: "Pending",
  },
  {
    id: 9,
    name: "Mia Roberts",
    registrationNo: "BTECH3839",
    currentOE: { OEName: "Signal Processing", courseCode: "SP102" },
    requestedOE: { OEName: "Robotics", courseCode: "RO201" },
    remainingSeats: 4,
    status: "Pending",
  },
  {
    id: 10,
    name: "Benjamin Lee",
    registrationNo: "BTECH4445",
    currentOE: { OEName: "Engineering Graphics", courseCode: "EG104" },
    requestedOE: { OEName: "Embedded Systems", courseCode: "ES205" },
    remainingSeats: 5,
    status: "Pending",
  },
  {
    id: 11,
    name: "Chris Adams",
    registrationNo: "BTECH2021",
    currentOE: { OEName: "Thermodynamics", courseCode: "TH305" },
    requestedOE: { OEName: "Cloud Computing", courseCode: "CC404" },
    remainingSeats: 2,
    status: "Pending",
  },
  {
    id: 12,
    name: "Jack Thomas",
    registrationNo: "BTECH3233",
    currentOE: { OEName: "Data Privacy", courseCode: "DP101" },
    requestedOE: { OEName: "Machine Learning", courseCode: "ML303" },
    remainingSeats: 1,
    status: "Pending",
  },
  {
    id: 13,
    name: "Olivia Scott",
    registrationNo: "BTECH3031",
    currentOE: { OEName: "Fluid Mechanics", courseCode: "FM202" },
    requestedOE: { OEName: "Artificial Intelligence", courseCode: "AI404" },
    remainingSeats: 3,
    status: "Pending",
  },
];
